services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_vagas
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
